### PR TITLE
Model definition language changed from theano to tensorflow

### PR DESCRIPTION
**Pull request by shashankg7**
Model part changed from theano to tensorflow.

### CODE REVIEW

**Comment by mAch17** [comment]
Hi @shashankg7 , great work with the tensorflow backend. I think lets give an option between theano/tensorflow and make tensorflow the default just like Keras.  (We use Theano internally at ParallelDots and will like to keep it theano compatible). Will it be possible for you to do that and resend PR ?

**Comment by shashankg7** [comment]
@mAch17 . Support for both theano and tensorflow added. Please review.

**Comment by mAch17** [comment]
Great. Pushing it for now, Will reopen the ticket if any issue comes up.

**Comment by shashankg7** [comment]
Sure, thanks.

**Pull request merged**
